// ============================================================================
// LegalHub Super App - Persian / English Translation System
// ============================================================================

type TranslationKey = string;

type TranslationEntry = {
  fa: string;
  en: string;
};

type Translations = Record<TranslationKey, TranslationEntry>;

export const translations: Translations = {
  // ============ AUTH ============
  'auth.login': { fa: 'ورود', en: 'Login' },
  'auth.register': { fa: 'ثبت نام', en: 'Register' },
  'auth.email': { fa: 'ایمیل', en: 'Email' },
  'auth.password': { fa: 'رمز عبور', en: 'Password' },
  'auth.confirmPassword': { fa: 'تکرار رمز عبور', en: 'Confirm Password' },
  'auth.firstName': { fa: 'نام', en: 'First Name' },
  'auth.lastName': { fa: 'نام خانوادگی', en: 'Last Name' },
  'auth.phone': { fa: 'شماره تلفن', en: 'Phone Number' },
  'auth.nationalCode': { fa: 'کد ملی', en: 'National Code' },
  'auth.role': { fa: 'نقش', en: 'Role' },
  'auth.rememberMe': { fa: 'مرا به خاطر بسپار', en: 'Remember Me' },
  'auth.forgotPassword': { fa: 'فراموشی رمز عبور', en: 'Forgot Password?' },
  'auth.loginButton': { fa: 'ورود به سیستم', en: 'Sign In' },
  'auth.registerButton': { fa: 'ایجاد حساب کاربری', en: 'Create Account' },
  'auth.noAccount': { fa: 'حساب کاربری ندارید؟', en: "Don't have an account?" },
  'auth.hasAccount': { fa: 'قبلاً ثبت نام کرده‌اید؟', en: 'Already have an account?' },
  'auth.logout': { fa: 'خروج', en: 'Logout' },
  'auth.twoFactor': { fa: 'تأیید دو مرحله‌ای', en: 'Two-Factor Auth' },
  'auth.invalidCredentials': { fa: 'ایمیل یا رمز عبور اشتباه است', en: 'Invalid email or password' },
  'auth.sessionExpired': { fa: 'نشست شما منقضی شده است', en: 'Your session has expired' },
  'auth.profile': { fa: 'پروفایل', en: 'Profile' },
  'auth.changePassword': { fa: 'تغییر رمز عبور', en: 'Change Password' },

  // ============ NAVIGATION ============
  'nav.dashboard': { fa: 'داشبورد', en: 'Dashboard' },
  'nav.cases': { fa: 'پرونده‌ها', en: 'Cases' },
  'nav.appointments': { fa: 'نوبت‌دهی', en: 'Appointments' },
  'nav.invoices': { fa: 'فاکتورها', en: 'Invoices' },
  'nav.payments': { fa: 'پرداخت‌ها', en: 'Payments' },
  'nav.tasks': { fa: 'وظایف', en: 'Tasks' },
  'nav.messages': { fa: 'پیام‌ها', en: 'Messages' },
  'nav.notifications': { fa: 'اعلان‌ها', en: 'Notifications' },
  'nav.documents': { fa: 'مدارک', en: 'Documents' },
  'nav.courses': { fa: 'دوره‌ها', en: 'Courses' },
  'nav.social': { fa: 'انجمن', en: 'Community' },
  'nav.calendar': { fa: 'تقویم', en: 'Calendar' },
  'nav.timeTracking': { fa: 'ثبت زمان', en: 'Time Tracking' },
  'nav.leads': { fa: 'مشتریان بالقوه', en: 'Leads' },
  'nav.users': { fa: 'کاربران', en: 'Users' },
  'nav.reports': { fa: 'گزارش‌ها', en: 'Reports' },
  'nav.settings': { fa: 'تنظیمات', en: 'Settings' },
  'nav.all': { fa: 'همه', en: 'All' },

  // ============ DASHBOARD ============
  'dashboard.title': { fa: 'داشبورد', en: 'Dashboard' },
  'dashboard.overview': { fa: 'نمای کلی', en: 'Overview' },
  'dashboard.stats': { fa: 'آمار', en: 'Statistics' },
  'dashboard.recentCases': { fa: 'پرونده‌های اخیر', en: 'Recent Cases' },
  'dashboard.upcomingAppointments': { fa: 'نوبت‌های آینده', en: 'Upcoming Appointments' },
  'dashboard.pendingTasks': { fa: 'وظایف در انتظار', en: 'Pending Tasks' },
  'dashboard.recentPayments': { fa: 'پرداخت‌های اخیر', en: 'Recent Payments' },
  'dashboard.totalRevenue': { fa: 'کل درآمد', en: 'Total Revenue' },
  'dashboard.openCases': { fa: 'پرونده‌های باز', en: 'Open Cases' },
  'dashboard.totalClients': { fa: 'کل موکلین', en: 'Total Clients' },
  'dashboard.activeTasks': { fa: 'وظایف فعال', en: 'Active Tasks' },
  'dashboard.upcomingHearings': { fa: 'جلسات دادگاه آینده', en: 'Upcoming Hearings' },
  'dashboard.unpaidInvoices': { fa: 'فاکتورهای پرداخت نشده', en: 'Unpaid Invoices' },
  'dashboard.welcome': { fa: 'خوش آمدید', en: 'Welcome' },
  'dashboard.myCartable': { fa: 'کارتابل من', en: 'My Cartable' },
  'dashboard.managerDashboard': { fa: 'داشبورد مدیریت', en: 'Manager Dashboard' },
  'dashboard.clientDashboard': { fa: 'داشبورد من', en: 'My Dashboard' },
  'dashboard.myCases': { fa: 'پرونده‌های من', en: 'My Cases' },
  'dashboard.myTasks': { fa: 'وظایف من', en: 'My Tasks' },
  'dashboard.myAppointments': { fa: 'نوبت‌های من', en: 'My Appointments' },
  'dashboard.myInvoices': { fa: 'فاکتورهای من', en: 'My Invoices' },
  'dashboard.myLawyers': { fa: 'وکلای من', en: 'My Lawyers' },
  'dashboard.myClients': { fa: 'موکلین من', en: 'My Clients' },
  'dashboard.teamPerformance': { fa: 'عملکرد تیم', en: 'Team Performance' },
  'dashboard.recentActivity': { fa: 'فعالیت‌های اخیر', en: 'Recent Activity' },

  // ============ CASES ============
  'cases.title': { fa: 'مدیریت پرونده‌ها', en: 'Case Management' },
  'cases.new': { fa: 'پرونده جدید', en: 'New Case' },
  'cases.edit': { fa: 'ویرایش پرونده', en: 'Edit Case' },
  'cases.delete': { fa: 'حذف پرونده', en: 'Delete Case' },
  'cases.caseNumber': { fa: 'شماره پرونده', en: 'Case Number' },
  'cases.title': { fa: 'عنوان پرونده', en: 'Case Title' },
  'cases.type': { fa: 'نوع پرونده', en: 'Case Type' },
  'cases.status': { fa: 'وضعیت', en: 'Status' },
  'cases.priority': { fa: 'اولویت', en: 'Priority' },
  'cases.description': { fa: 'توضیحات', en: 'Description' },
  'cases.summary': { fa: 'خلاصه', en: 'Summary' },
  'cases.court': { fa: 'دادگاه', en: 'Court' },
  'cases.courtBranch': { fa: 'شعبه دادگاه', en: 'Court Branch' },
  'cases.judge': { fa: 'قاضی', en: 'Judge' },
  'cases.filingDate': { fa: 'تاریخ ثبت', en: 'Filing Date' },
  'cases.nextHearing': { fa: 'جلسه بعدی', en: 'Next Hearing' },
  'cases.lawyer': { fa: 'وکیل', en: 'Lawyer' },
  'cases.client': { fa: 'موکل', en: 'Client' },
  'cases.intern': { fa: 'کارآموز', en: 'Intern' },
  'cases.tags': { fa: 'برچسب‌ها', en: 'Tags' },
  'cases.closedAt': { fa: 'تاریخ بستن', en: 'Closed At' },
  'cases.closedReason': { fa: 'دلیل بستن', en: 'Close Reason' },
  'cases.documents': { fa: 'مدارک پرونده', en: 'Case Documents' },
  'cases.timeline': { fa: 'تاریخچه', en: 'Timeline' },
  'cases.comments': { fa: 'نظرات', en: 'Comments' },
  'cases.notes': { fa: 'یادداشت‌ها', en: 'Notes' },
  'cases.hearings': { fa: 'جلسات دادگاه', en: 'Hearings' },
  'cases.deadlines': { fa: 'مهلت‌ها', en: 'Deadlines' },
  'cases.invoices': { fa: 'فاکتورها', en: 'Invoices' },
  'cases.addDocument': { fa: 'افزودن مدرک', en: 'Add Document' },
  'cases.addComment': { fa: 'افزودن نظر', en: 'Add Comment' },
  'cases.addNote': { fa: 'افزودن یادداشت', en: 'Add Note' },
  'cases.addHearing': { fa: 'افزودن جلسه', en: 'Add Hearing' },
  'cases.addDeadline': { fa: 'افزودن مهلت', en: 'Add Deadline' },
  'cases.search': { fa: 'جستجوی پرونده', en: 'Search Cases' },
  'cases.filter': { fa: 'فیلتر', en: 'Filter' },

  // Case Types
  'caseType.civil': { fa: 'حقوقی', en: 'Civil' },
  'caseType.criminal': { fa: 'کیفری', en: 'Criminal' },
  'caseType.family': { fa: 'خانوادگی', en: 'Family' },
  'caseType.corporate': { fa: 'شرکتی', en: 'Corporate' },
  'caseType.labor': { fa: 'کار و تأمین', en: 'Labor' },
  'caseType.tax': { fa: 'مالیاتی', en: 'Tax' },
  'caseType.ip': { fa: 'مالکیت فکری', en: 'Intellectual Property' },
  'caseType.immigration': { fa: 'مهاجرتی', en: 'Immigration' },

  // Case Statuses
  'caseStatus.OPEN': { fa: 'باز', en: 'Open' },
  'caseStatus.IN_PROGRESS': { fa: 'در حال بررسی', en: 'In Progress' },
  'caseStatus.PENDING': { fa: 'در انتظار', en: 'Pending' },
  'caseStatus.CLOSED': { fa: 'بسته شده', en: 'Closed' },
  'caseStatus.ARCHIVED': { fa: 'بایگانی شده', en: 'Archived' },

  // Case Priorities
  'priority.LOW': { fa: 'کم', en: 'Low' },
  'priority.MEDIUM': { fa: 'متوسط', en: 'Medium' },
  'priority.HIGH': { fa: 'زیاد', en: 'High' },
  'priority.URGENT': { fa: 'فوری', en: 'Urgent' },

  // ============ APPOINTMENTS ============
  'appointments.title': { fa: 'نوبت‌دهی', en: 'Appointments' },
  'appointments.new': { fa: 'نوبت جدید', en: 'New Appointment' },
  'appointments.edit': { fa: 'ویرایش نوبت', en: 'Edit Appointment' },
  'appointments.date': { fa: 'تاریخ', en: 'Date' },
  'appointments.startTime': { fa: 'ساعت شروع', en: 'Start Time' },
  'appointments.endTime': { fa: 'ساعت پایان', en: 'End Time' },
  'appointments.type': { fa: 'نوع نوبت', en: 'Type' },
  'appointments.description': { fa: 'توضیحات', en: 'Description' },
  'appointments.notes': { fa: 'یادداشت', en: 'Notes' },
  'appointments.videoLink': { fa: 'لینک ویدیو', en: 'Video Link' },
  'appointments.reminder': { fa: 'یادآوری', en: 'Reminder' },
  'appointments.confirm': { fa: 'تأیید نوبت', en: 'Confirm Appointment' },
  'appointments.cancel': { fa: 'لغو نوبت', en: 'Cancel Appointment' },
  'appointments.today': { fa: 'نوبت‌های امروز', en: 'Today Appointments' },
  'appointments.week': { fa: 'این هفته', en: 'This Week' },

  // Appointment Types
  'appointmentType.IN_PERSON': { fa: 'حضوری', en: 'In Person' },
  'appointmentType.VIDEO': { fa: 'ویدیویی', en: 'Video Call' },
  'appointmentType.PHONE': { fa: 'تلفنی', en: 'Phone Call' },

  // Appointment Statuses
  'appointmentStatus.PENDING': { fa: 'در انتظار', en: 'Pending' },
  'appointmentStatus.CONFIRMED': { fa: 'تأیید شده', en: 'Confirmed' },
  'appointmentStatus.CANCELLED': { fa: 'لغو شده', en: 'Cancelled' },
  'appointmentStatus.COMPLETED': { fa: 'تکمیل شده', en: 'Completed' },
  'appointmentStatus.NO_SHOW': { fa: 'حاضر نشد', en: 'No Show' },

  // ============ INVOICES ============
  'invoices.title': { fa: 'فاکتورها', en: 'Invoices' },
  'invoices.new': { fa: 'فاکتور جدید', en: 'New Invoice' },
  'invoices.number': { fa: 'شماره فاکتور', en: 'Invoice Number' },
  'invoices.amount': { fa: 'مبلغ', en: 'Amount' },
  'invoices.tax': { fa: 'مالیات', en: 'Tax' },
  'invoices.discount': { fa: 'تخفیف', en: 'Discount' },
  'invoices.total': { fa: 'مبلغ کل', en: 'Total' },
  'invoices.dueDate': { fa: 'تاریخ سررسید', en: 'Due Date' },
  'invoices.paidAmount': { fa: 'مبلغ پرداخت شده', en: 'Paid Amount' },
  'invoices.paidAt': { fa: 'تاریخ پرداخت', en: 'Paid At' },
  'invoices.notes': { fa: 'یادداشت', en: 'Notes' },
  'invoices.print': { fa: 'چاپ فاکتور', en: 'Print Invoice' },
  'invoices.pay': { fa: 'پرداخت', en: 'Pay' },
  'invoices.overdue': { fa: 'سررسید گذشته', en: 'Overdue' },

  // Invoice Statuses
  'invoiceStatus.PENDING': { fa: 'در انتظار', en: 'Pending' },
  'invoiceStatus.PAID': { fa: 'پرداخت شده', en: 'Paid' },
  'invoiceStatus.PARTIAL': { fa: 'پرداخت جزئی', en: 'Partial' },
  'invoiceStatus.OVERDUE': { fa: 'سررسید گذشته', en: 'Overdue' },
  'invoiceStatus.CANCELLED': { fa: 'لغو شده', en: 'Cancelled' },

  // ============ PAYMENTS ============
  'payments.title': { fa: 'پرداخت‌ها', en: 'Payments' },
  'payments.new': { fa: 'ثبت پرداخت', en: 'New Payment' },
  'payments.method': { fa: 'روش پرداخت', en: 'Payment Method' },
  'payments.transactionId': { fa: 'شماره تراکنش', en: 'Transaction ID' },
  'payments.description': { fa: 'توضیحات', en: 'Description' },
  'payments.wallet': { fa: 'کیف پول', en: 'Wallet' },
  'payments.balance': { fa: 'موجودی', en: 'Balance' },

  // Payment Methods
  'paymentMethod.CARD': { fa: 'کارت بانکی', en: 'Bank Card' },
  'paymentMethod.BANK_TRANSFER': { fa: 'انتقال بانکی', en: 'Bank Transfer' },
  'paymentMethod.CASH': { fa: 'نقدی', en: 'Cash' },
  'paymentMethod.WALLET': { fa: 'کیف پول', en: 'Wallet' },
  'paymentMethod.INSTALLMENT': { fa: 'اقساط', en: 'Installment' },

  // Payment Statuses
  'paymentStatus.PENDING': { fa: 'در انتظار', en: 'Pending' },
  'paymentStatus.COMPLETED': { fa: 'تکمیل شده', en: 'Completed' },
  'paymentStatus.FAILED': { fa: 'ناموفق', en: 'Failed' },
  'paymentStatus.REFUNDED': { fa: 'بازپرداخت شده', en: 'Refunded' },

  // ============ TASKS ============
  'tasks.title': { fa: 'مدیریت وظایف', en: 'Task Management' },
  'tasks.new': { fa: 'وظیفه جدید', en: 'New Task' },
  'tasks.edit': { fa: 'ویرایش وظیفه', en: 'Edit Task' },
  'tasks.dueDate': { fa: 'مهلت', en: 'Due Date' },
  'tasks.completedAt': { fa: 'تاریخ تکمیل', en: 'Completed At' },
  'tasks.assignedTo': { fa: 'اختصاص به', en: 'Assigned To' },
  'tasks.createdBy': { fa: 'ایجاد توسط', en: 'Created By' },
  'tasks.markDone': { fa: 'تکمیل وظیفه', en: 'Mark Done' },
  'tasks.myTasks': { fa: 'وظایف من', en: 'My Tasks' },
  'tasks.overdue': { fa: 'سررسید گذشته', en: 'Overdue' },

  // Task Statuses
  'taskStatus.TODO': { fa: 'انجام نشده', en: 'To Do' },
  'taskStatus.IN_PROGRESS': { fa: 'در حال انجام', en: 'In Progress' },
  'taskStatus.DONE': { fa: 'تکمیل شده', en: 'Done' },
  'taskStatus.CANCELLED': { fa: 'لغو شده', en: 'Cancelled' },

  // ============ MESSAGES ============
  'messages.title': { fa: 'پیام‌ها', en: 'Messages' },
  'messages.new': { fa: 'پیام جدید', en: 'New Message' },
  'messages.send': { fa: 'ارسال', en: 'Send' },
  'messages.reply': { fa: 'پاسخ', en: 'Reply' },
  'messages.search': { fa: 'جستجوی پیام', en: 'Search Messages' },
  'messages.unread': { fa: 'خوانده نشده', en: 'Unread' },
  'messages.markRead': { fa: 'خوانده شد', en: 'Mark as Read' },
  'messages.conversations': { fa: 'مکالمات', en: 'Conversations' },
  'messages.noMessages': { fa: 'پیامی وجود ندارد', en: 'No messages' },
  'messages.typeMessage': { fa: 'پیام خود را بنویسید...', en: 'Type a message...' },

  // ============ NOTIFICATIONS ============
  'notifications.title': { fa: 'اعلان‌ها', en: 'Notifications' },
  'notifications.markAllRead': { fa: 'خواندن همه', en: 'Mark All Read' },
  'notifications.clear': { fa: 'پاک کردن', en: 'Clear All' },
  'notifications.unread': { fa: 'خوانده نشده', en: 'Unread' },
  'notifications.noNotifications': { fa: 'اعلانی وجود ندارد', en: 'No notifications' },

  // Notification Types
  'notificationType.INFO': { fa: 'اطلاعات', en: 'Info' },
  'notificationType.WARNING': { fa: 'هشدار', en: 'Warning' },
  'notificationType.ERROR': { fa: 'خطا', en: 'Error' },
  'notificationType.SUCCESS': { fa: 'موفقیت', en: 'Success' },

  // ============ DOCUMENTS ============
  'documents.title': { fa: 'مدارک', en: 'Documents' },
  'documents.new': { fa: 'بارگذاری مدرک', en: 'Upload Document' },
  'documents.name': { fa: 'نام فایل', en: 'File Name' },
  'documents.type': { fa: 'نوع فایل', en: 'File Type' },
  'documents.size': { fa: 'حجم', en: 'Size' },
  'documents.category': { fa: 'دسته‌بندی', en: 'Category' },
  'documents.version': { fa: 'نسخه', en: 'Version' },
  'documents.download': { fa: 'دانلود', en: 'Download' },
  'documents.delete': { fa: 'حذف', en: 'Delete' },
  'documents.search': { fa: 'جستجوی مدرک', en: 'Search Documents' },

  // Document Categories
  'docCategory.legal': { fa: 'حقوقی', en: 'Legal' },
  'docCategory.contract': { fa: 'قرارداد', en: 'Contract' },
  'docCategory.financial': { fa: 'مالی', en: 'Financial' },
  'docCategory.template': { fa: 'قالب', en: 'Template' },
  'docCategory.report': { fa: 'گزارش', en: 'Report' },
  'docCategory.other': { fa: 'سایر', en: 'Other' },

  // ============ COURSES / LMS ============
  'courses.title': { fa: 'دوره‌های آموزشی', en: 'Courses' },
  'courses.new': { fa: 'دوره جدید', en: 'New Course' },
  'courses.edit': { fa: 'ویرایش دوره', en: 'Edit Course' },
  'courses.enroll': { fa: 'ثبت‌نام', en: 'Enroll' },
  'courses.progress': { fa: 'پیشرفت', en: 'Progress' },
  'courses.duration': { fa: 'مدت زمان', en: 'Duration' },
  'courses.instructor': { fa: 'مدرس', en: 'Instructor' },
  'courses.lessons': { fa: 'درس‌ها', en: 'Lessons' },
  'courses.exam': { fa: 'آزمون', en: 'Exam' },
  'courses.certificate': { fa: 'گواهینامه', en: 'Certificate' },
  'courses.myCourses': { fa: 'دوره‌های من', en: 'My Courses' },
  'courses.completed': { fa: 'تکمیل شده', en: 'Completed' },
  'courses.webinar': { fa: 'وبینار', en: 'Webinar' },

  // Course Statuses
  'courseStatus.DRAFT': { fa: 'پیش‌نویس', en: 'Draft' },
  'courseStatus.PUBLISHED': { fa: 'منتشر شده', en: 'Published' },
  'courseStatus.ARCHIVED': { fa: 'بایگانی', en: 'Archived' },

  // ============ SOCIAL / COMMUNITY ============
  'social.title': { fa: 'انجمن', en: 'Community' },
  'social.newPost': { fa: 'پست جدید', en: 'New Post' },
  'social.discussion': { fa: 'بحث', en: 'Discussion' },
  'social.article': { fa: 'مقاله', en: 'Article' },
  'social.announcement': { fa: 'اطلاعیه', en: 'Announcement' },
  'social.question': { fa: 'سؤال', en: 'Question' },
  'social.knowledge': { fa: 'دانش', en: 'Knowledge' },
  'social.likes': { fa: 'لایک', en: 'Likes' },
  'social.comment': { fa: 'نظر', en: 'Comment' },
  'social.addComment': { fa: 'افزودن نظر', en: 'Add Comment' },
  'social.pinned': { fa: 'پین شده', en: 'Pinned' },

  // ============ CALENDAR ============
  'calendar.title': { fa: 'تقویم', en: 'Calendar' },
  'calendar.newEvent': { fa: 'رویداد جدید', en: 'New Event' },
  'calendar.meeting': { fa: 'جلسه', en: 'Meeting' },
  'calendar.deadline': { fa: 'مهلت', en: 'Deadline' },
  'calendar.hearing': { fa: 'جلسه دادگاه', en: 'Hearing' },
  'calendar.reminder': { fa: 'یادآوری', en: 'Reminder' },
  'calendar.month': { fa: 'ماه', en: 'Month' },
  'calendar.week': { fa: 'هفته', en: 'Week' },
  'calendar.day': { fa: 'روز', en: 'Day' },
  'calendar.today': { fa: 'امروز', en: 'Today' },

  // ============ TIME TRACKING ============
  'timeTracking.title': { fa: 'ثبت زمان', en: 'Time Tracking' },
  'timeTracking.new': { fa: 'ثبت زمان جدید', en: 'New Time Entry' },
  'timeTracking.date': { fa: 'تاریخ', en: 'Date' },
  'timeTracking.hours': { fa: 'ساعت', en: 'Hours' },
  'timeTracking.description': { fa: 'توضیحات', en: 'Description' },
  'timeTracking.totalHours': { fa: 'مجموع ساعت‌ها', en: 'Total Hours' },
  'timeTracking.billed': { fa: 'صورت‌حساب شده', en: 'Billed' },
  'timeTracking.unbilled': { fa: 'صورت‌حساب نشده', en: 'Unbilled' },
  'timeTracking.weeklyReport': { fa: 'گزارش هفتگی', en: 'Weekly Report' },

  // ============ LEADS / CRM ============
  'leads.title': { fa: 'مشتریان بالقوه', en: 'Leads' },
  'leads.new': { fa: 'مشتری جدید', en: 'New Lead' },
  'leads.name': { fa: 'نام', en: 'Name' },
  'leads.source': { fa: 'منبع', en: 'Source' },
  'leads.value': { fa: 'ارزش', en: 'Value' },
  'leads.assignedTo': { fa: 'اختصاص به', en: 'Assigned To' },
  'leads.notes': { fa: 'یادداشت', en: 'Notes' },
  'leads.convert': { fa: 'تبدیل به موکل', en: 'Convert to Client' },

  // Lead Statuses
  'leadStatus.NEW': { fa: 'جدید', en: 'New' },
  'leadStatus.CONTACTED': { fa: 'تماس گرفته شده', en: 'Contacted' },
  'leadStatus.QUALIFIED': { fa: 'واجد شرایط', en: 'Qualified' },
  'leadStatus.CONVERTED': { fa: 'تبدیل شده', en: 'Converted' },
  'leadStatus.LOST': { fa: 'از دست رفته', en: 'Lost' },

  // ============ USERS ============
  'users.title': { fa: 'مدیریت کاربران', en: 'User Management' },
  'users.new': { fa: 'کاربر جدید', en: 'New User' },
  'users.edit': { fa: 'ویرایش کاربر', en: 'Edit User' },
  'users.delete': { fa: 'حذف کاربر', en: 'Delete User' },
  'users.list': { fa: 'لیست کاربران', en: 'User List' },
  'users.search': { fa: 'جستجوی کاربر', en: 'Search Users' },
  'users.active': { fa: 'فعال', en: 'Active' },
  'users.inactive': { fa: 'غیرفعال', en: 'Inactive' },
  'users.verified': { fa: 'تأیید شده', en: 'Verified' },

  // Roles
  'role.SUPER_ADMIN': { fa: 'مدیر ارشد', en: 'Super Admin' },
  'role.COMPLEX_MANAGER': { fa: 'مدیر مجتمع', en: 'Complex Manager' },
  'role.LAWYER': { fa: 'وکیل', en: 'Lawyer' },
  'role.INTERN': { fa: 'کارآموز', en: 'Intern' },
  'role.CLIENT': { fa: 'موکل', en: 'Client' },
  'role.ACCOUNTANT': { fa: 'حسابدار', en: 'Accountant' },
  'role.SUPPORT_STAFF': { fa: 'پشتیبان', en: 'Support Staff' },

  // ============ REPORTS ============
  'reports.title': { fa: 'گزارش‌ها', en: 'Reports' },
  'reports.financial': { fa: 'گزارش مالی', en: 'Financial Report' },
  'reports.cases': { fa: 'گزارش پرونده‌ها', en: 'Cases Report' },
  'reports.performance': { fa: 'گزارش عملکرد', en: 'Performance Report' },
  'reports.export': { fa: 'خروجی', en: 'Export' },
  'reports.pdf': { fa: 'خروجی PDF', en: 'Export PDF' },
  'reports.excel': { fa: 'خروجی Excel', en: 'Export Excel' },
  'reports.dateRange': { fa: 'بازه زمانی', en: 'Date Range' },
  'reports.fromDate': { fa: 'از تاریخ', en: 'From Date' },
  'reports.toDate': { fa: 'تا تاریخ', en: 'To Date' },

  // ============ SETTINGS ============
  'settings.title': { fa: 'تنظیمات', en: 'Settings' },
  'settings.general': { fa: 'تنظیمات عمومی', en: 'General' },
  'settings.profile': { fa: 'پروفایل', en: 'Profile' },
  'settings.security': { fa: 'امنیت', en: 'Security' },
  'settings.notifications': { fa: 'اعلان‌ها', en: 'Notifications' },
  'settings.language': { fa: 'زبان', en: 'Language' },
  'settings.theme': { fa: 'پوسته', en: 'Theme' },
  'settings.light': { fa: 'روشن', en: 'Light' },
  'settings.dark': { fa: 'تاریک', en: 'Dark' },
  'settings.save': { fa: 'ذخیره', en: 'Save' },
  'settings.cancel': { fa: 'انصراف', en: 'Cancel' },

  // ============ HEARINGS ============
  'hearings.title': { fa: 'جلسات دادگاه', en: 'Hearings' },
  'hearings.new': { fa: 'جلسه جدید', en: 'New Hearing' },
  'hearings.date': { fa: 'تاریخ', en: 'Date' },
  'hearings.time': { fa: 'ساعت', en: 'Time' },
  'hearings.location': { fa: 'مکان', en: 'Location' },
  'hearings.judge': { fa: 'قاضی', en: 'Judge' },

  // Hearing Statuses
  'hearingStatus.SCHEDULED': { fa: 'برنامه‌ریزی شده', en: 'Scheduled' },
  'hearingStatus.COMPLETED': { fa: 'تکمیل شده', en: 'Completed' },
  'hearingStatus.CANCELLED': { fa: 'لغو شده', en: 'Cancelled' },
  'hearingStatus.POSTPONED': { fa: 'به تعویق افتاده', en: 'Postponed' },

  // ============ CONTRACTS ============
  'nav.contracts': { fa: 'قراردادها', en: 'Contracts' },
  'contracts.title': { fa: 'کتابخانه قراردادها', en: 'Contract Library' },
  'contracts.search': { fa: 'جستجوی قرارداد...', en: 'Search contracts...' },
  'contracts.allCategories': { fa: 'همه دسته‌ها', en: 'All Categories' },
  'contracts.allDifficulties': { fa: 'همه سطوح', en: 'All Levels' },
  'contracts.general': { fa: 'عمومی', en: 'General' },
  'contracts.specialized': { fa: 'تخصصی', en: 'Specialized' },
  'contracts.advanced': { fa: 'پیشرفته', en: 'Advanced' },
  'contracts.totalContracts': { fa: 'مجموع قراردادها', en: 'Total Contracts' },
  'contracts.categories': { fa: 'دسته‌بندی‌ها', en: 'Categories' },
  'contracts.applicableLaws': { fa: 'قوانین مرتبط', en: 'Applicable Laws' },
  'contracts.copyText': { fa: 'کپی متن', en: 'Copy Text' },
  'contracts.copied': { fa: 'کپی شد!', en: 'Copied!' },
  'contracts.downloadCount': { fa: 'دانلود', en: 'Downloads' },
  'contracts.viewCount': { fa: 'مشاهده', en: 'Views' },
  'contracts.noResults': { fa: 'قراردادی یافت نشد', en: 'No contracts found' },
  'contracts.version': { fa: 'نسخه', en: 'Version' },

  // ============ COMMON / UTILITY ============
  'common.save': { fa: 'ذخیره', en: 'Save' },
  'common.cancel': { fa: 'انصراف', en: 'Cancel' },
  'common.delete': { fa: 'حذف', en: 'Delete' },
  'common.edit': { fa: 'ویرایش', en: 'Edit' },
  'common.create': { fa: 'ایجاد', en: 'Create' },
  'common.search': { fa: 'جستجو', en: 'Search' },
  'common.filter': { fa: 'فیلتر', en: 'Filter' },
  'common.sort': { fa: 'مرتب‌سازی', en: 'Sort' },
  'common.export': { fa: 'خروجی', en: 'Export' },
  'common.import': { fa: 'ورودی', en: 'Import' },
  'common.refresh': { fa: 'بازنشانی', en: 'Refresh' },
  'common.loading': { fa: 'در حال بارگذاری...', en: 'Loading...' },
  'common.noData': { fa: 'داده‌ای وجود ندارد', en: 'No data available' },
  'common.error': { fa: 'خطا', en: 'Error' },
  'common.success': { fa: 'موفقیت', en: 'Success' },
  'common.warning': { fa: 'هشدار', en: 'Warning' },
  'common.confirm': { fa: 'تأیید', en: 'Confirm' },
  'common.yes': { fa: 'بله', en: 'Yes' },
  'common.no': { fa: 'خیر', en: 'No' },
  'common.close': { fa: 'بستن', en: 'Close' },
  'common.back': { fa: 'بازگشت', en: 'Back' },
  'common.next': { fa: 'بعدی', en: 'Next' },
  'common.previous': { fa: 'قبلی', en: 'Previous' },
  'common.view': { fa: 'مشاهده', en: 'View' },
  'common.download': { fa: 'دانلود', en: 'Download' },
  'common.upload': { fa: 'بارگذاری', en: 'Upload' },
  'common.actions': { fa: 'عملیات', en: 'Actions' },
  'common.details': { fa: 'جزئیات', en: 'Details' },
  'common.more': { fa: 'بیشتر', en: 'More' },
  'common.showAll': { fa: 'نمایش همه', en: 'Show All' },
  'common.copy': { fa: 'کپی', en: 'Copy' },
  'common.copied': { fa: 'کپی شد', en: 'Copied' },
  'common.total': { fa: 'مجموع', en: 'Total' },
  'common.subtotal': { fa: 'جمع فرعی', en: 'Subtotal' },
  'common.currency': { fa: 'تومان', en: 'Toman' },
  'common.date': { fa: 'تاریخ', en: 'Date' },
  'common.time': { fa: 'ساعت', en: 'Time' },
  'common.name': { fa: 'نام', en: 'Name' },
  'common.description': { fa: 'توضیحات', en: 'Description' },
  'common.status': { fa: 'وضعیت', en: 'Status' },
  'common.active': { fa: 'فعال', en: 'Active' },
  'common.inactive': { fa: 'غیرفعال', en: 'Inactive' },
  'common.required': { fa: 'الزامی', en: 'Required' },
  'common.optional': { fa: 'اختیاری', en: 'Optional' },
  'common.submit': { fa: 'ارسال', en: 'Submit' },
  'common.reset': { fa: 'بازنشانی', en: 'Reset' },
  'common.apply': { fa: 'اعمال', en: 'Apply' },
  'common.offline': { fa: 'آفلاین', en: 'Offline' },
  'common.online': { fa: 'آنلاین', en: 'Online' },
  'common.avatar': { fa: 'تصویر پروفایل', en: 'Avatar' },
  'common.fullname': { fa: 'نام کامل', en: 'Full Name' },
  'common.areYouSure': { fa: 'آیا مطمئن هستید؟', en: 'Are you sure?' },
  'common.deleteConfirm': { fa: 'این عمل قابل بازگشت نیست', en: 'This action cannot be undone' },

  // ============ MISC / EXTRA ============
  'misc.toman': { fa: 'تومان', en: 'Toman' },
  'misc.perHour': { fa: 'ساعتی', en: 'Per Hour' },
  'misc.rating': { fa: 'امتیاز', en: 'Rating' },
  'misc.experience': { fa: 'سابقه کار', en: 'Experience' },
  'misc.years': { fa: 'سال', en: 'Years' },
  'misc.specialization': { fa: 'تخصص', en: 'Specialization' },
  'misc.bio': { fa: 'بیوگرافی', en: 'Bio' },
  'misc.education': { fa: 'تحصیلات', en: 'Education' },
  'misc.languages': { fa: 'زبان‌ها', en: 'Languages' },
  'misc.company': { fa: 'شرکت', en: 'Company' },
  'misc.address': { fa: 'آدرس', en: 'Address' },
  'misc.city': { fa: 'شهر', en: 'City' },
  'misc.province': { fa: 'استان', en: 'Province' },
  'misc.postalCode': { fa: 'کد پستی', en: 'Postal Code' },
  'misc.occupation': { fa: 'شغل', en: 'Occupation' },
  'misc.university': { fa: 'دانشگاه', en: 'University' },
  'misc.field': { fa: 'رشته', en: 'Field' },
  'misc.supervisor': { fa: 'سرپرست', en: 'Supervisor' },
  'misc.startDate': { fa: 'تاریخ شروع', en: 'Start Date' },
  'misc.endDate': { fa: 'تاریخ پایان', en: 'End Date' },
  'misc.score': { fa: 'نمره', en: 'Score' },
  'misc.passed': { fa: 'قبول', en: 'Passed' },
  'misc.failed': { fa: 'مردود', en: 'Failed' },
  'misc.pagination': { fa: 'صفحه‌بندی', en: 'Pagination' },
  'misc.page': { fa: 'صفحه', en: 'Page' },
  'misc.of': { fa: 'از', en: 'of' },
  'misc.results': { fa: 'نتایج', en: 'Results' },
  'misc.noResults': { fa: 'نتیجه‌ای یافت نشد', en: 'No results found' },
  'misc.select': { fa: 'انتخاب کنید', en: 'Select' },
  'misc.all': { fa: 'همه', en: 'All' },
  'misc.none': { fa: 'هیچکدام', en: 'None' },
};

// ============ TRANSLATION HELPER ============

export function t(key: string, lang: 'fa' | 'en' = 'fa'): string {
  return translations[key]?.[lang] || key;
}

export type Language = 'fa' | 'en';
